// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZrrpGggGdYUqDUGCFy6BeLy9UmQ6qyY',
    appId: '1:94172739971:web:76833e5a78ccc917111eb6',
    messagingSenderId: '94172739971',
    projectId: 'whereismybus-372b8',
    authDomain: 'whereismybus-372b8.firebaseapp.com',
    storageBucket: 'whereismybus-372b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFJSyFYxm9alA0A4nSYsvmfzyYiFZPEc',
    appId: '1:94172739971:android:c37a61b5ce28df9d111eb6',
    messagingSenderId: '94172739971',
    projectId: 'whereismybus-372b8',
    storageBucket: 'whereismybus-372b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu8dF0vcdFdjJXFf2-l-GVJr68dO8bqsw',
    appId: '1:94172739971:ios:4910b29122158154111eb6',
    messagingSenderId: '94172739971',
    projectId: 'whereismybus-372b8',
    storageBucket: 'whereismybus-372b8.appspot.com',
    iosBundleId: 'com.example.whereIsMyBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu8dF0vcdFdjJXFf2-l-GVJr68dO8bqsw',
    appId: '1:94172739971:ios:0e8cacdcc633e14e111eb6',
    messagingSenderId: '94172739971',
    projectId: 'whereismybus-372b8',
    storageBucket: 'whereismybus-372b8.appspot.com',
    iosBundleId: 'com.example.whereIsMyBus.RunnerTests',
  );
}
